import type { Sessao } from './types'

export const mockSessaoResultado: Sessao = {
  sessao_id: 'mock-local',
  nome_condominio: 'Condomínio Demonstração',
  ano_previsao: 2026,
  criado_em: new Date().toISOString(),
  modelo_ia: '',
  ia_ativa: true,
  resumo: {
    base_total: 322450.8,
    desconsideracoes: 28750.25,
    prov_laudo: 4200,
    prov_incendio: 1850,
    subtotal: 299750.55,
    inflacao: 0.0472,
    total_previsto: 313899.57,
    receita_anual: 326400,
    receita_mensal: 27200,
    periodo: ['2025-01-01', '2025-12-31'],
    impacto_receita_mensal: 1320,
  },
  extraordinarias: [
    {
      id: 1,
      grupo: 'Conservação',
      classe: 'Reparo emergencial do portão',
      data: '2025-07-14',
      descricao: 'Reparo emergencial do motor do portão - parcela 1/2',
      valor: 7800,
      motivo: 'IA: evento pontual com descrição de reparo e parcela identificada',
      n_meses: 1,
      origem: 'IA',
      decisao: 'aprovada',
      nota: 'Retirado por não representar custo mensal recorrente.',
      explicacao: {
        resumo: 'Retirado da previsão porque foi identificado como reparo pontual, não como despesa mensal do condomínio.',
        evidencias: [
          'A descrição informa parcela 1/2.',
          'A frequência observada foi 1/12 meses.',
          'A decisão reduz a base recorrente para não inflar a taxa.',
        ],
      },
    },
    {
      id: 2,
      grupo: 'Obras/Benfeitorias',
      classe: 'Pintura da fachada',
      data: '2025-10-03',
      descricao: 'Sinal de pintura da fachada',
      valor: 20950.25,
      motivo: 'Grupo Obras/Benfeitorias — evento pontual de capital',
      n_meses: 1,
      origem: 'Regra',
      decisao: 'aprovada',
      explicacao: {
        resumo: 'Retirado da previsão por ser obra/benfeitoria, ou seja, gasto de capital não recorrente.',
        evidencias: [
          'Classificação por grupo de obra.',
          'Aconteceu em apenas 1 mês do período.',
        ],
      },
    },
  ],
  revisar: [
    {
      id: 3,
      grupo: 'Contratos',
      classe: 'Manutenção de câmeras',
      data: '2025-05-10',
      descricao: 'Visita técnica e troca de conectores',
      valor: 3600,
      motivo: 'Classe periódica/ambígua, mantida na base após revisão',
      n_meses: 6,
      origem: 'Regra',
      decisao: 'reprovada',
      nota: 'Apesar da visita técnica, o condomínio costuma ter manutenção semestral.',
      explicacao: {
        resumo: 'Mantido na previsão porque o padrão indica manutenção periódica e não um evento isolado.',
        evidencias: [
          'A conta apareceu em 6/12 meses.',
          'A nota humana confirma recorrência semestral.',
        ],
      },
    },
  ],
  inadimplencia: [
    {
      id: 1,
      unidade: '301 - João da Silva',
      classe: 'Tx. Condomínio',
      mes_ref: '10/2025',
      vencimento: '2025-10-10',
      valor: 1320,
      meses_atraso: 4,
      critica: true,
      decisao: 'abater',
      explicacao: {
        resumo: 'Abatido da leitura de receita porque representa atraso crítico e reduz a arrecadação provável.',
        evidencias: ['4 meses em atraso.', 'Classificado como inadimplência crítica.'],
      },
    },
    {
      id: 2,
      unidade: '502 - Maria Pereira',
      classe: 'Fundo Reserva',
      mes_ref: '12/2025',
      vencimento: '2025-12-10',
      valor: 145,
      meses_atraso: 1,
      critica: false,
      decisao: 'ignorar',
    },
  ],
  inad_meta: { total: 1465, critica: 1320, data_base: '2026-01-10' },
  linhas_contas: [
    { grupo: 'Despesas com Pessoal', classe: 'Folha e encargos', base: 132000, deducao: 0, final: 132000, regra: 'Recorrente', n_meses: 12 },
    { grupo: 'Tarifas Públicas', classe: 'Água do Condomínio', base: 48600, deducao: 0, final: 48600, regra: 'Recorrente', n_meses: 12 },
    { grupo: 'Tarifas Públicas', classe: 'Luz do Condomínio', base: 21800, deducao: 0, final: 21800, regra: 'Recorrente', n_meses: 12 },
    { grupo: 'Conservação', classe: 'Reparo emergencial do portão', base: 12800, deducao: 7800, final: 5000, regra: 'Decisão humana: removido evento pontual', n_meses: 1 },
    { grupo: 'Obras/Benfeitorias', classe: 'Pintura da fachada', base: 20950.25, deducao: 20950.25, final: 0, regra: 'R1: Obras/Benfeitorias', n_meses: 1 },
    { grupo: 'Contratos', classe: 'Administração', base: 33600, deducao: 0, final: 33600, regra: 'Recorrente', n_meses: 12 },
    { grupo: 'Contratos', classe: 'Manutenção de câmeras', base: 3600, deducao: 0, final: 3600, regra: 'Mantido na revisão', n_meses: 6 },
    { grupo: 'Despesas Administrativas', classe: 'Correio e expediente', base: 7250.3, deducao: 0, final: 7250.3, regra: 'Recorrente', n_meses: 10 },
  ],
  previsao_final: [
    { row: 9, label: 'RECEITAS', anual: 'VALOR MENSAL', rateio: null, mensal: null },
    { row: 10, label: 'Taxas de Condomínio', anual: 24800, rateio: null, mensal: null },
    { row: 11, label: 'Fundo de Reserva', anual: 2400, rateio: null, mensal: null },
    { row: 19, label: 'TOTAL', anual: 27200, rateio: null, mensal: null },
    { row: 21, label: 'DESPESAS', anual: 'VALOR MENSAL', rateio: null, mensal: null },
    { row: 22, label: 'Despesas com Pessoal', anual: 11000, rateio: null, mensal: null },
    { row: 23, label: 'Água do Condomínio', anual: 4050, rateio: null, mensal: null },
    { row: 24, label: 'Luz do Condomínio', anual: 1816.67, rateio: null, mensal: null },
    { row: 25, label: 'Contratos', anual: 3100, rateio: null, mensal: null },
    { row: 26, label: 'Conservação', anual: 416.67, rateio: null, mensal: null },
    { row: 27, label: 'Despesas Administrativas', anual: 604.19, rateio: null, mensal: null },
    { row: 47, label: 'SUBTOTAL', anual: 24979.21, rateio: null, mensal: null },
    { row: 48, label: 'PREVISÃO DE INFLAÇÃO - 4,72%', anual: 1179.76, rateio: null, mensal: null },
    { row: 50, label: 'TOTAL', anual: 26158.3, rateio: null, mensal: null },
    { row: 52, label: 'SALDO ( SUPERÁVIT )', anual: 1041.7, rateio: null, mensal: null },
  ],
  fluxo_mensal: [
    { mes: 'Jan', receita: 27100, despesa: 23800, saldo: 3300 },
    { mes: 'Fev', receita: 27050, despesa: 24600, saldo: 2450 },
    { mes: 'Mar', receita: 27200, despesa: 25550, saldo: 1650 },
    { mes: 'Abr', receita: 27350, despesa: 24100, saldo: 3250 },
    { mes: 'Mai', receita: 27180, despesa: 26400, saldo: 780 },
    { mes: 'Jun', receita: 27220, despesa: 25200, saldo: 2020 },
    { mes: 'Jul', receita: 27090, despesa: 30900, saldo: -3810 },
    { mes: 'Ago', receita: 27320, despesa: 24750, saldo: 2570 },
    { mes: 'Set', receita: 27140, despesa: 25100, saldo: 2040 },
    { mes: 'Out', receita: 27280, despesa: 33200, saldo: -5920 },
    { mes: 'Nov', receita: 27310, despesa: 25900, saldo: 1410 },
    { mes: 'Dez', receita: 27160, despesa: 27050, saldo: 110 },
  ],
  status: 'gerado',
}
